import os

OPENAI_TEMPERATURE = 0.9
EMBEDDING_MODEL = "text-embedding-3-large"
EMBEDDING_DIMENSION = 3072
BREAKPOINT_THRESHOLD_TYPE = "gradient"
BREAKPOINT_THRESHOLD_AMOUNT = 82.0
MIN_CHUNK_SIZE = 300
CONTRACT_VECTORSTORE_SIMILARITY_THRESHOLD = 0.1
CONTRACT_VECTORSTORE_LIMIT = 3
CHAT_HISTORY_K = 5
SUPABASE_TABLE_NAME = "contract_vector_store"
SUPABASE_QUERY_NAME = "match_contracts"
SUPABASE_SUMMARY_TABLE_NAME = "chat_summaries"
SUPABASE_SUMMARY_QUERY_NAME = "match_summaries"
OPENAI_MODEL = "gpt-4.1-mini"
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_PROJECT = "parentcopilot"
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
LANGCHAIN_API_KEY = os.getenv("LANGCHAIN_API_KEY")
#